<?php 

$data = $block->getStoreLocations();

$list_locations = array();
$index = 0;

$init_location = '';

?>

<script src="http://maps.google.com/maps/api/js?key=AIzaSyCCgSB0qxmvrWTT6OVDjbfIZJoTtErCZuM" type="text/javascript"></script>
<div id="map"></div>
<div id="list-location">
	<ul>
	<?php foreach($data as $location): ?>
	<?php 
			$list_locations[] = "['".$location['LocationName']."', ".$location['LongLat'].", ".$index++."]";
			$init_location = $location['LongLat'];
	?>
	  <li>
		<h4><?php echo $location['LocationName'] ?></h4>
		<span><b><?php echo __('Address: ') ?></b><?php echo $location['StoreAddress'] ?></span>
		<span><b><?php echo __('Phone: ') ?></b><?php echo $location['StorePhone'] ?></span>
		<span><b><?php echo __('Store Hours: ') ?></b><?php echo $location['StoreHours'] ?></span>
		
	  </li>
	 <?php endforeach ?>
	</ul>
</div>

  <script type="text/javascript">
	/*     var locations = [
      ['Bondi Beach', -33.890542, 151.274856, 4],
      ['Coogee Beach', -33.923036, 151.259052, 5],
      ['Cronulla Beach', -34.028249, 151.157507, 3],
      ['Manly Beach', -33.80010128657071, 151.28747820854187, 2],
      ['Maroubra Beach', -33.950198, 151.259302, 1]
    ]; */
	
	var locations = [<?php echo implode(",",$list_locations) ?>];

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 10,
      center: new google.maps.LatLng(<?php echo $init_location ?>),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  </script>
